apiVersion: v1
kind: Pod
metadata:
  name: apache-with-datera-external-volume
  labels:
    app: httpd
spec:
  containers:
  - name: apache
    image: centos/httpd:latest
    imagePullPolicy: IfNotPresent
    ports:
    - name: web
      containerPort: 80
      protocol: TCP
    volumeMounts:
    - mountPath: "/var/www/html"
      name: html
  volumes:
  - name: html
    persistentVolumeClaim:
      claimName: sample-volume-claim
  dnsPolicy: ClusterFirst
  restartPolicy: Always
