---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jira-volume-claim
spec:
# we set datera as the default storage class
# so no need to specify a class
# storageClassName: datera
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jira
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31080
  selector:
    app: jira
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: jira
  name: jira
  namespace:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: jira
    spec:
      # set the pod to mount volumes as the pod user
      # to prevent pod fails to write on the volumes
      securityContext:
        fsGroup: 1
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - "jirapg"
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: remove-lost-found
        image: busybox:1.25.0
        command: ["rm", "-rf", "/var/atlassian/jira/lost+found"]
        volumeMounts:
        - mountPath: /var/atlassian/jira
          name: data
      - name: wait-for-postgres
        image: jwilder/dockerize:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          value: jirapg
        - name: DB_PORT
          value: "5432"
        command: ["dockerize", "-wait", "tcp://$(DB_HOST):$(DB_PORT)", "-timeout", "30s"]
      containers:
      - name: jira
        env:
        - name: DB_TYPE
          value: postgres72
        - name: DB_HOST
          value: jirapg
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: jiradb
        - name: DB_USER
          value: jiradbuser
        - name: DB_PASSWORD
          value: jiradbuser
        - name: JVM_MINIMUM_MEMORY
          value: "512m"
        - name: JVM_MAXIMUM_MEMORY
          value: "1024m"
        image: kalise/atlassian-jira:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 120
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 60
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/atlassian/jira
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: jira-volume-claim
