---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: consul
  namespace:
  labels:
    type: statefulset
spec:
  serviceName: consul
  replicas: 3
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul:latest
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - name: rpc
          containerPort: 8300
        - name: lan
          containerPort: 8301
        - name: wan
          containerPort: 8302
        - name: http
          containerPort: 8500
        - name: dns
          containerPort: 8600
        volumeMounts:
        - name: consuldata
          mountPath: /consul/data
        args:
        - agent
        - -server
        - -datacenter=kubernetes
        - -data-dir=/consul/data
        - -log-level=trace
        - -client=0.0.0.0
        - -advertise=$(POD_IP)
        - -advertise-wan=127.0.0.1
        - -serf-wan-bind=127.0.0.1
        - -bootstrap-expect=3
        - -retry-join=consul-0.consul.$(POD_NAMESPACE).svc.cluster.local
        - -retry-join=consul-1.consul.$(POD_NAMESPACE).svc.cluster.local
        - -retry-join=consul-2.consul.$(POD_NAMESPACE).svc.cluster.local
        - -domain=cluster.local
        - -ui
  volumeClaimTemplates:
  - metadata:
      name: consuldata
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: datera-storage-class      
