---
apiVersion: v1
kind: Service
metadata:
  name: consul-service
  labels:
    app: consul
spec:
  type: NodePort
  ports:
  - name: ui
    port: 8500
    targetPort: 8500
    nodePort: 31085
  selector:
    app: consul
