kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datera-volume-claim
  namespace: 
spec:
  storageClassName: datera
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
