kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datera-volume-claim
  namespace: 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      manual: 'true'
